name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Ruby ${{ matrix.ruby }} / ${{ matrix.gemfile }}"
    strategy:
      matrix:
        ruby:
          - '3.2'
          - '3.3'
          - '3.4'
        gemfile:
          - rails_7_0
          - rails_7_1
          - rails_7_2
          - rails_8_0
          - rails_8_1
          - rails_8_2

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake
